spring:
  profiles:
    active: dev
wechat:
    mpAppId: wxd898fcb01713c658
    mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
    mchId: 1483469312
    mchKey: C5245D70627C1F8E9964D494B0735025
    keyPath: /var/weixin_cert/h5.p12
    notifyUrl: http://selllinhaoprod.mynatapp.cc/sell/pay/notify