spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1/test?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379

server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: C:\sellLog\sell.log
#  level: info